### ISSUE TITLE
Unread Indicator

### ISSUE THREAD

**Issue by christophlandon** [edipox/n1-ido#29]
Hi Epido,

Thank you so much for your information! You had asked that for further communication, to write you here.  Unfortunately, not being a coder, I wouldn't even know where to begin as all this is a little over my head. I'll continue with it and hopefully I'll figure out on how this is done.

All the best!

Cheers,
Chris

```
================================
```

Hi Chris,

Thank you! 

You could add something like:
```css
.thread-list .thread-icon.thread-icon-unread,
.draft-list .thread-icon.thread-icon-unread{ 
  background: @ido-sidebar--default;
}
```
to some file, for example, https://github.com/edipox/n1-ido/blob/master/styles/threads.less

The problem with that "unread" indicator is that it's an image so you probably need to replace it with another image. Or you could also add radious to that component and decrease its size in order to achieve something similar to what you are expecting
```css
.thread-list .thread-icon.thread-icon-unread,
.draft-list .thread-icon.thread-icon-unread{ 
    background: @ido-sidebar--default;
    width: 15px;
    height: 15px;
    border-radius: 90px;
}
```

Please for any further question or feature request create an issue in the repository https://github.com/edipox/n1-ido/issues

Hope it was helpful,

Best regards!
